"""Genie prepares explicitly enrolled new Sparks using the bundled recipes."""
import json
from datetime import datetime, timezone
import urllib.error
import urllib.parse
import urllib.request

TOOLSET = 'stargate_spark_setup'
NAMES = {'repair_spark_connection', 'spark_connection_status', 'request_spark_access', 'bootstrap_spark_access', 'spark_access_status', 'discover_sparks', 'spark_discovery_status', 'resume_spark_preparation', 'enroll_spark', 'enroll_discovered_spark', 'qualify_spark_media', 'setup_spark', 'spark_setup_status', 'prepare_spark', 'qualify_spark_llm', 'register_spark_llm'}


def register_spark_setup(config, emit):
    from tools.registry import registry
    url = urllib.parse.urlsplit(config['url'])
    if (url.scheme != 'http' or url.hostname != '127.0.0.1' or not url.port or url.path != '/api/genie/spark-setup-tools'
            or url.username or url.password or url.query or url.fragment):
        raise ValueError('Use the private Spark setup tool endpoint')

    class NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs): return None

    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}), NoRedirect())

    def run(name, args):
        if name in {'request_spark_access', 'bootstrap_spark_access', 'spark_access_status'}:
            allowed = {'scan_id', 'endpoint_ids'} if name == 'request_spark_access' else {'access_id'}
            if not isinstance(args, dict) or set(args) - allowed:
                return json.dumps({'error': 'Use only saved access or discovery IDs. Enter credentials in the local dashboard, never in tools.'})
        event = {'tool': name, 'request': args, 'at': datetime.now(timezone.utc).isoformat()}
        emit('spark_setup', event={**event, 'state': 'reading'})
        try:
            payload = {'action': 'status'} if name == 'spark_setup_status' else {'action': 'repair_connection' if name == 'repair_spark_connection' else 'connection_status' if name == 'spark_connection_status' else 'request_access' if name == 'request_spark_access' else 'bootstrap_access' if name == 'bootstrap_spark_access' else 'access_status' if name == 'spark_access_status' else 'discover' if name == 'discover_sparks' else 'discovery_status' if name == 'spark_discovery_status' else 'resume' if name == 'resume_spark_preparation' else 'enroll_discovered' if name == 'enroll_discovered_spark' else 'enroll' if name == 'enroll_spark' else 'qualify_media' if name == 'qualify_spark_media' else 'setup' if name == 'setup_spark' else 'register' if name == 'register_spark_llm' else 'qualify' if name == 'qualify_spark_llm' else 'start', **args}
            request = urllib.request.Request(config['url'], data=json.dumps(payload).encode(), headers={'Content-Type': 'application/json', 'X-SG-Spark-Setup-Tool': config['token']})
            with opener.open(request, timeout=150 if name in {'enroll_spark', 'enroll_discovered_spark', 'repair_spark_connection', 'spark_connection_status'} else 30) as response:
                raw = response.read(524289)
                if len(raw) > 524288: raise ValueError('Setup status too large')
                result = json.loads(raw)
            emit('spark_setup', event={**event, 'state': 'complete', 'finished_at': datetime.now(timezone.utc).isoformat(), 'result': result})
            return json.dumps(result)
        except Exception as error:
            message = ('Connection request was not confirmed. Read spark_connection_status with the same repair_id; do not start a replacement.' if name == 'repair_spark_connection' else 'Setup request was not confirmed. Read spark_setup_status for the same target; do not start a replacement.')
            if isinstance(error, urllib.error.HTTPError):
                try: message = json.loads(error.read(4096)).get('error', message)
                except (ValueError, OSError): pass
                finally: error.close()
            emit('spark_setup', event={**event, 'state': 'failed', 'error': message})
            return json.dumps({'error': message, 'target_id': args.get('target_id'), **({'repair_id': args.get('repair_id')} if name == 'repair_spark_connection' else {})})

    schemas = [
        ('spark_connection_status', 'Read existing configured SSH connections and retained authenticated discovery identity availability, or a saved repair_id receipt. No network login or trust write. Historical evidence is not current reachability. Use this when an enrolled connection fails host-key verification; do not enroll it as a new machine or ask the owner to accept an unverified key.', {'type': 'object', 'properties': {'repair_id': {'type': 'string'}}, 'additionalProperties': False}),
        ('repair_spark_connection', 'Reconcile one existing configured SSH connection using retained authenticated discovery evidence. Supply its exact connection name and a fresh repair_id UUID, preserving that ID on uncertainty. Rechecks the same destination, pinned host key and hardware identity, backs up normal known_hosts before adding only a missing entry, then verifies ordinary strict SSH. Refuses conflicting keys, changed destinations or identities, and unauthenticated scan pins. Does not alter remote keys, launchers, models, containers, firmware or SSH config. Requires the enabled Spark setup switch and owner-requested maintenance. A failed inspection proves no service state. After an uncertain write or process restart, the same ID only performs read-only reconciliation, never repeats promotion; complete or failed receipts are returned unchanged. Read spark_connection_status after uncertain acknowledgment. A verified connection is not recovered model service.', {'type': 'object', 'properties': {'connection': {'type': 'string'}, 'repair_id': {'type': 'string'}}, 'required': ['connection', 'repair_id'], 'additionalProperties': False}),
        ('request_spark_access', 'For owner-requested onboarding, select one to eight initial_access_available endpoint IDs from an existing scan. Prepares a local dashboard credential form; no host change occurs. Tell the owner to enter the shared username and password in DSG > Gate Genie > New Spark access, never in any chat or tool call. Requires New Spark setup. Endpoint addresses are observations, not yet proven new machines. Follow the same access_id; the owner grant wakes this conversation.', {'type': 'object', 'properties': {'scan_id': {'type': 'string'}, 'endpoint_ids': {'type': 'array', 'items': {'type': 'string'}, 'minItems': 1, 'maxItems': 8}}, 'required': ['scan_id', 'endpoint_ids'], 'additionalProperties': False}),
        ('bootstrap_spark_access', 'Use a saved access_id with the owner local credential grant to prove new GB10 hardware, back up authorized_keys, add an existing gateway public key and verify key-only access. Does not change models, firmware, SSH daemon settings or existing key restrictions. Password stays out of tools and conversation. Runs detached; read spark_access_status once, then finish and wait for the saved follow-up. Reconcile this same ID after uncertainty; never reissue a possible key write. A completed access request needs fresh discovery and identity-bound enrollment before the original owner-requested setup can continue.', {'type': 'object', 'properties': {'access_id': {'type': 'string'}}, 'required': ['access_id'], 'additionalProperties': False}),
        ('spark_access_status', 'Read saved initial-access state without contacting hosts. Optional access_id selects one request. Report exact key_ready, credentials_required, verification_pending or blocked states. Key readiness is not enrollment, model setup or firmware readiness. Credentials lost on dashboard restart must be entered again locally; no chat password request.', {'type': 'object', 'properties': {'access_id': {'type': 'string'}}, 'additionalProperties': False}),
        ('discover_sparks', 'Find candidate Sparks on the gateway connected private networks and read neighbor evidence from known Spark connections. Uses previously configured SSH usernames and keys; optional username only if the owner supplies one. Requires Server inspection; it does not enable New Spark setup. Does not enroll, configure, flash firmware, reboot or change network settings. Returns a durable scan ID while read-only inspection runs; follow spark_discovery_status for that same scan. Distinguish hardware-verified candidates from open SSH ports, existing machines and peer-scoped addresses. Coverage is partial; do not claim missing machines are absent or setup-ready. Never invent addresses or claim firmware support.', {'type': 'object', 'properties': {'username': {'type': 'string'}}, 'additionalProperties': False}),
        ('spark_discovery_status', 'Read a saved discovery scan without launching another scan or contacting hosts. Supply the original scan_id for a specific scan, or omit it for the latest. Report its exact running/completed/uncertain state and coverage issues. A discovered machine is not enrolled or qualified. Count candidate hardware identities, not endpoints. Existing machines verified through configured aliases remain listed when direct-IP authentication fails. Reported interface addresses do not establish a working direct SSH path. Remote IPv6 link-local zones are not gateway interfaces; remote IPv4 observations alone establish neither reachability nor unreachability.', {'type': 'object', 'properties': {'scan_id': {'type': 'string'}}, 'additionalProperties': False}),
        ('resume_spark_preparation', 'Resume the same confirmed failed new-Spark preparation after inspecting the failure and addressing its cause. Supply its exact finished_at from spark_setup_status. Reuses verified retained sources, downloads, builds and stopped containers. Never resumes uncertain or running work, never restarts native qualification, and does not change recipes. An enabled setup switch grants permission. Check status once afterward and report; do not repeatedly retry a recurring failure. A saved full setup request continues after preparation succeeds.', {'type': 'object', 'properties': {'target_id': {'type': 'string'}, 'expected_finished_at': {'type': 'string'}}, 'required': ['target_id', 'expected_finished_at'], 'additionalProperties': False}),
        ('enroll_discovered_spark', 'Enroll a hardware-verified new candidate using its exact saved scan_id and candidate_id and a new target_id; no owner-supplied IP is needed. Rechecks the pinned SSH key and hardware identity, preserves existing trust and backs it up before adding only this verified host key, then verifies ordinary SSH and saves the target. Requires New Spark setup. Existing machines and changed configured connections are refused. Does not build or start models, change SSH configuration or install firmware. Read readiness/issues and continue only the owner-requested setup. On uncertain response read setup status before retrying these same IDs. For eligible unauthenticated IPv4 endpoints use request_spark_access first; IPv6-only setup remains unavailable. Never ask for passwords in chat.', {'type': 'object', 'properties': {'scan_id': {'type': 'string'}, 'candidate_id': {'type': 'string'}, 'target_id': {'type': 'string'}}, 'required': ['scan_id', 'candidate_id', 'target_id'], 'additionalProperties': False}),
        ('enroll_spark', 'Connect a new Spark supplied by the owner: use their exact IPv4 address or hostname and SSH username, plus a new target ID. Checks SSH key access and host prerequisites, then saves enrollment for setup_spark without a dashboard restart. Does not build, start or stop engines. Never guess an address or repurpose an existing worker. Read returned readiness/issues before requesting setup. Never ask for passwords or private keys in chat; explain any SSH access prerequisite. The enabled New Spark setup switch grants permission.', {'type': 'object', 'properties': {'target_id': {'type': 'string'}, 'host': {'type': 'string'}, 'username': {'type': 'string'}}, 'required': ['target_id', 'host', 'username'], 'additionalProperties': False}),
        ('qualify_spark_media', 'Test the prepared stopped H3 and ACE-Step engines on a new idle Spark before its LLM is started. Generates real sample video/audio and music, retains and fully decodes the files, and stops only those prepared engines. Detached from chat. After acceptance, read spark_setup_status once before ending. Only a saved setup_spark request creates later automatic chat wakeups. Existing serving LLMs are untouched. The setup switch grants permission; read status and inspect the same retained operation on uncertainty. Does not enroll media or recovery.', {'type': 'object', 'properties': {'target_id': {'type': 'string'}}, 'required': ['target_id'], 'additionalProperties': False}),
        ('setup_spark', 'Request complete LLM onboarding for an enrolled new Spark: prepare the standard engines, test stopped media candidates where connected, then qualify and register the LLM. A saved request wakes Genie after each long stage, across dashboard restarts. The enabled setup switch grants permission; turning it off pauses new stages while accepted work continues. Registration connects the qualified dedicated recovery helper and any separately qualified, unchanged media engines. Existing recovery and media capability switches keep their settings. After a resolved prerequisite or a no-action reply, call this again only when the owner asks to continue: the saved workflow rechecks current status. It does not rerun a failed native operation; confirmed failed preparation uses resume_spark_preparation. Never repeatedly rearm an unchanged failure. Use prepare_spark instead for preparation only.', {'type': 'object', 'properties': {'target_id': {'type': 'string'}}, 'required': ['target_id'], 'additionalProperties': False}),
        ('register_spark_llm', 'Admit the qualified new LLM to the gateway. Rechecks its actual running instance, model/context and saved native proof; records observed configuration, adds a paused worker through existing gateway controls, then resumes it if operator state is unchanged. The setup switch grants permission as part of requested new-Spark setup. Does not modify an existing worker. New restart-qualified proofs enroll the dedicated recovery helper; separately qualified unchanged media engines enroll their switching bindings. Earlier LLM-only proofs remain LLM-only. Report the actual returned state and services fields; capability switches are unchanged.', {'type': 'object', 'properties': {'target_id': {'type': 'string'}}, 'required': ['target_id'], 'additionalProperties': False}),
        ('qualify_spark_llm', 'Start and qualify the prepared LLM on an idle enrolled new Spark. Installs a dedicated bundled recovery helper, tests one same-container restart, then checks exact serving settings and native text/tools/vision/context/cache/EOS behavior. This proves that restart but does not enroll automatic recovery. Runs independently of this chat and leaves a passing LLM running for later registration. Does not stop existing workloads or register a server. Read setup status first; once a qualification exists, inspect it instead of rerunning.', {'type': 'object', 'properties': {'target_id': {'type': 'string'}}, 'required': ['target_id'], 'additionalProperties': False}),
        ('spark_setup_status', 'Read preparation progress for enrolled new Sparks. Distinguishes accepted, running, prepared stopped engines and failures. Prepared engines are not qualified or serving.', {'type': 'object', 'properties': {}, 'additionalProperties': False}),
        ('prepare_spark', 'Prepare the pinned LLM, H3 and ACE engines on an explicitly enrolled idle new Spark. The enabled setup switch grants standing permission. Builds and downloads continue independently of this chat. Never stops existing services. Read status first and once after acceptance; do not poll indefinitely. Qualification and gateway registration are still separate steps.', {'type': 'object', 'properties': {'target_id': {'type': 'string'}}, 'required': ['target_id'], 'additionalProperties': False}),
    ]
    for name, description, parameters in schemas:
        registry.register(name=name, toolset=TOOLSET, schema={'name': name, 'description': description, 'parameters': parameters}, handler=lambda args, _name=name, **kw: run(_name, args), max_result_size_chars=524288)
    return NAMES
