import {createHash} from 'node:crypto';import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {hermesProvider} from './genie-hermes.mjs';import {GenieChat} from './genie-chat.mjs';
test('installed Hermes inspects local oMLX through the real collector without exposing its credential',{skip:!process.env.DSG_TEST_HERMES_SOURCE||!process.env.DSG_TEST_HERMES_PYTHON,timeout:120000},async t=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'sg-local-inspection-')),root=path.join(directory,'omlx');fs.mkdirSync(path.join(root,'state'),{recursive:true});
 const secret='LOCAL_INSPECTION_FIXTURE_KEY',key=path.join(directory,'key');fs.writeFileSync(key,secret,{mode:0o600});fs.writeFileSync(path.join(root,'serve.sh'),`exec omlx serve --api-key ${secret} --max-context 262144\n`);fs.writeFileSync(path.join(root,'state','settings.json'),JSON.stringify({api_key:secret,cache:{size:'372GB'}}));fs.writeFileSync(path.join(root,'state','model_settings.json'),JSON.stringify({example:{mtp_enabled:true}}));fs.writeFileSync(path.join(root,'server.pid'),String(process.pid));
 let count=0,nativeReads=0;const requests=[];
 const server=http.createServer((req,res)=>{if(req.method==='GET'){if(req.headers.authorization===`Bearer ${secret}`)nativeReads++;res.end(JSON.stringify({data:[{id:'example-model',max_model_len:262144}]}));return;}let raw='';req.on('data',chunk=>raw+=chunk);req.on('end',()=>{
  const body=JSON.parse(raw);requests.push(body);count++;const message=count===1?{role:'assistant',content:null,tool_calls:[{id:'local-inspection',type:'function',function:{name:'tool_call',arguments:JSON.stringify({name:'inspect_server',arguments:{worker_id:'example'}})}}]}:{role:'assistant',content:'I inspected the local oMLX configuration without changing its service.'};
  const delta={...message,...(message.tool_calls?{tool_calls:message.tool_calls.map((v,index)=>({...v,index}))}:{})};
  if(body.stream){res.setHeader('content-type','text/event-stream');res.end('data: '+JSON.stringify({id:'local',model:'example-model',choices:[{index:0,delta,finish_reason:null}]})+'\n\ndata: '+JSON.stringify({id:'local',model:'example-model',choices:[{index:0,delta:{},finish_reason:count===1?'tool_calls':'stop'}]})+'\n\ndata: [DONE]\n\n');}
  else res.end(JSON.stringify({id:'local',model:'example-model',choices:[{message,finish_reason:count===1?'tool_calls':'stop'}]}));
 });});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${server.address().port}/v1`;
 const provider=hermesProvider({python:process.env.DSG_TEST_HERMES_PYTHON,source:process.env.DSG_TEST_HERMES_SOURCE,url,model:'example-model',inspection:{workers:{example:{kind:'omlx-local',root,url,api_key_file:key}}}},{directory});
 t.after(()=>{provider.close();server.closeAllConnections();server.close();fs.rmSync(directory,{recursive:true,force:true});});
 const chat=new GenieChat({directory:path.join(directory,'chat'),provider,getSnapshot:()=>({gateway:{workers:[{id:'example'}]}})}),conversation=chat.create();chat.submit(conversation.id,'Inspect the enrolled local oMLX server.','local-inspection');await chat.idle();
 const reply=chat.get(conversation.id).messages[1];assert.equal(reply.state,'complete',JSON.stringify(reply));assert.equal(nativeReads,1);assert.equal(count,2);const event=reply.inspection.events.find(e=>e.state==='complete');assert.equal(event.result.runtime,'omlx');assert.equal(event.result.files['state/model_settings.json'].content.example.mtp_enabled,true);assert.equal(event.result.process.recorded_pid_matches_listener,true);assert.doesNotMatch(JSON.stringify([reply,requests]),new RegExp(secret));assert.match(JSON.stringify(requests[1].messages),/372GB/);assert.equal(provider.info.can_act,false);
});
test('native Hermes calls all inspection tools and retains evidence without server authority',{skip:!process.env.DSG_TEST_HERMES_SOURCE||!process.env.DSG_TEST_HERMES_PYTHON,timeout:120000},async t=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'sg-inspection-'));const records=path.join(directory,'records');fs.mkdirSync(path.join(records,'observed'),{recursive:true});fs.writeFileSync(path.join(records,'observed','example.json'),JSON.stringify({schema:1,worker_id:'example',kind:'observed',configuration:{context_length:262144,api_key:'PRIVATE_SECRET_VALUE'}}));
 const artifact=path.join(records,'artifacts','manifest.json');fs.mkdirSync(path.dirname(artifact));fs.writeFileSync(artifact,JSON.stringify({original_model_verification:{revision:'example-public-model-revision'},api_key:'PRIVATE_SECRET_VALUE'}));const child=path.join(records,'artifacts','tool-result.json');fs.writeFileSync(child,JSON.stringify({tool_calls:[{function:{name:'report_value',arguments:'{"value":7319}'}}],api_key:'PRIVATE_SECRET_VALUE'}));const manifest=JSON.parse(fs.readFileSync(artifact));manifest.validation_reference={path:'artifacts/tool-result.json',sha256:createHash('sha256').update(fs.readFileSync(child)).digest('hex')};fs.writeFileSync(artifact,JSON.stringify(manifest));const recordFile=path.join(records,'observed','example.json'),record=JSON.parse(fs.readFileSync(recordFile));record.configuration.baseline_reconciliation={path:artifact,sha256:createHash('sha256').update(fs.readFileSync(artifact)).digest('hex')};record.restoration={drill:{receipt_reference:{path:artifact,sha256:createHash('sha256').update(fs.readFileSync(artifact)).digest('hex')}}};fs.writeFileSync(recordFile,JSON.stringify(record));
 const bin=path.join(directory,'bin');fs.mkdirSync(bin);fs.writeFileSync(path.join(bin,'ssh'),'#!/bin/sh\ncat >/dev/null\nprintf \'%s\\n\' \'{"observed_at":"2026-01-01T00:00:00Z","container":{"running":true,"command":["--max-model-len","262144"]},"scope":"Synthetic live collector result"}\'\n',{mode:0o755});
 const defaults=path.join(records,'defaults');fs.mkdirSync(defaults);fs.writeFileSync(path.join(defaults,'shared.json'),JSON.stringify({schema:1,workers:['example'],selected_image:'sha256:'+'a'.repeat(64),selection_receipt_reference:{path:'artifacts/manifest.json',sha256:createHash('sha256').update(fs.readFileSync(artifact)).digest('hex')}}));
 const prior=process.env.PATH;process.env.PATH=bin+':'+prior;let count=0;const requests=[];
 const server=http.createServer((req,res)=>{if(req.method==='GET'){res.end(JSON.stringify({data:[{id:'example-model',context_length:131072}]}));return;}let body='';req.on('data',c=>body+=c);req.on('end',()=>{const p=JSON.parse(body);requests.push(p);count++;let message;if(count<=6)message={role:'assistant',content:null,tool_calls:[{id:'inspect-'+count,type:'function',function:{name:'tool_call',arguments:JSON.stringify({name:count===1?'read_server_configuration':count===2||count===4?'inspect_server':'read_server_artifact',arguments:{worker_id:'example',...(count===3?{artifact:'baseline_reconciliation',record_kind:'observed'}:{}),...(count===4?{selected_default:true}:{}),...(count===5?{artifact:'restoration_drill',record_kind:'observed'}:{}),...(count===6?{record_kind:'observed',reference_chain:['/configuration/baseline_reconciliation','/validation_reference']}:{})}})}}]};else message={role:'assistant',content:'I read the recorded configuration and inspected the configured server. The context is 262144. No server was changed.'};if(p.stream){res.setHeader('content-type','text/event-stream');const delta={...message,...(message.tool_calls?{tool_calls:message.tool_calls.map((v,index)=>({index,...v}))}:{})};res.write('data: '+JSON.stringify({id:'example-response',model:'example-model',choices:[{index:0,delta,finish_reason:null}]})+'\n\n');res.end('data: '+JSON.stringify({id:'example-response',model:'example-model',choices:[{index:0,delta:{},finish_reason:count<=6?'tool_calls':'stop'}],usage:{prompt_tokens:100,completion_tokens:30,total_tokens:130}})+'\n\ndata: [DONE]\n\n');}else{res.setHeader('content-type','application/json');res.end(JSON.stringify({id:'example-response',model:'example-model',choices:[{index:0,message,finish_reason:count<=6?'tool_calls':'stop'}],usage:{prompt_tokens:100,completion_tokens:30,total_tokens:130}}));}});});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const provider=hermesProvider({python:process.env.DSG_TEST_HERMES_PYTHON,source:process.env.DSG_TEST_HERMES_SOURCE,url:`http://127.0.0.1:${server.address().port}/v1`,model:'example-model',research:{search_url:`http://127.0.0.1:${server.address().port}`,extract_url:`http://127.0.0.1:${server.address().port}`},inspection:{records_directory:records,workers:{example:{ssh:['example-host'],container:'example-engine'}}}},{directory});
 t.after(()=>{process.env.PATH=prior;provider.close();server.closeAllConnections();server.close();fs.rmSync(directory,{recursive:true,force:true});});
 const chat=new GenieChat({directory:path.join(directory,'chat'),provider,getSnapshot:()=>({gateway:{workers:[{id:'example'}]}})});const c=chat.create();chat.submit(c.id,'Inspect the configured server and compare with its record.','native-inspection');await chat.idle();const reply=chat.get(c.id).messages[1];assert.equal(reply.state,'complete',JSON.stringify(reply));assert.equal(count,7);assert.deepEqual(requests[0].tools.map(x=>x.function.name).sort(),['tool_call','tool_describe','tool_search','web_extract','web_search']);assert.equal(provider.info.can_act,false);
 const completed=reply.inspection.events.filter(e=>e.state==='complete');assert.deepEqual(completed.map(e=>e.kind),['records','live','records','live','records','records']);assert.equal(completed[1].result.container.running,true);assert.doesNotMatch(JSON.stringify(reply),/PRIVATE_SECRET_VALUE/);assert.match(JSON.stringify(requests[2].messages),/Synthetic live collector result/);
 assert.deepEqual(completed.map(e=>e.operation),['read_server_configuration','inspect_server','read_server_artifact','inspect_server','read_server_artifact','read_server_artifact']);assert.equal(completed[2].result.hash_matches_record,true);assert.equal(completed[3].selected_default,true);assert.equal(completed[4].artifact,'restoration_drill');assert.equal(completed[4].result.hash_matches_record,true);assert.equal(completed[4].result.sha256,record.restoration.drill.receipt_reference.sha256);assert.equal(completed[0].result.selected_defaults.entries[0].selection_receipt.status,'verified');assert.equal(completed[0].result.selected_defaults.entries[0].record.selected_image,'sha256:'+'a'.repeat(64));assert.match(JSON.stringify(requests[3].messages),/example-public-model-revision/);
 assert.equal(completed[5].result.verified_references.length,2);assert.equal(completed[5].result.content.tool_calls[0].function.name,'report_value');assert.match(JSON.stringify(requests[6].messages),/report_value/);
 const reloaded=new GenieChat({directory:path.join(directory,'chat'),provider});assert.deepEqual(reloaded.get(c.id).messages[1].inspection,reply.inspection);
});
