import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {GenieChat} from './genie-chat.mjs';import {createChatDemo} from '../examples/genie-chat-demo.mjs';
const turn=()=>new Promise(resolve=>setImmediate(resolve));
function setup(t,extra={}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sg-stop-')),calls=[];t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const provider={generate:p=>new Promise((resolve,reject)=>{const call={...p,resolve,reject,aborted:false};calls.push(call);p.signal.addEventListener('abort',()=>{call.aborted=true;reject(new DOMException('Aborted','AbortError'));},{once:true});})};const chat=new GenieChat({directory:dir,provider,...extra});return {chat,calls,dir,provider};}
test('manual stop targets one reply, preserves partial context, and pauses its queued follow-ups',async t=>{
 const {chat,calls}=setup(t),a=chat.create(),b=chat.create();chat.submit(a.id,'First','first-stop-test');chat.submit(b.id,'Other','other-stop-test');await turn();calls[0].onDelta('Saved partial.');chat.submit(a.id,'Follow up','queued-stop-test');const id=chat.get(a.id).messages[1].id;
 chat.stop(a.id,id);chat.stop(a.id,id);await turn();assert.equal(calls[0].aborted,true);assert.equal(calls[1].aborted,false);assert.equal(chat.get(a.id).queue_paused,id);assert.equal(chat.get(a.id).messages[1].text,'Saved partial.');assert.equal(chat.get(a.id).messages[1].state,'interrupted');
 calls[0].onDelta('Late output');calls[0].onProgress({phase:'reasoning',step:99,reasoning_chars:100});assert.equal(chat.get(a.id).messages[1].text,'Saved partial.');assert.notEqual(chat.get(a.id).messages[1].progress?.step,99);
 assert.throws(()=>chat.stop(b.id,id),/not found/);chat.resume(a.id,id);await turn();assert.equal(calls.length,3);assert.equal(calls[2].message,'Follow up');assert.match(calls[2].history.find(m=>m.role==='assistant').content,/Saved partial.*\n\[This partial reply was stopped/);calls[2].resolve({text:'Continued'});calls[1].resolve({text:'Uninterrupted'});await chat.idle();
 chat.stop(a.id,id);assert.equal(chat.get(a.id).messages[3].state,'complete');assert.equal(chat.get(b.id).messages[1].text,'Uninterrupted');
 const reopened=new GenieChat({directory:chat.directory,provider:{generate:()=>{throw Error('Must not replay');}}});assert.equal(reopened.get(a.id).messages[1].state,'interrupted');assert.equal(reopened.get(a.id).messages[1].text,'Saved partial.');
});
test('stopping an undispatched queued reply never cancels the earlier active answer',async t=>{
 const {chat,calls}=setup(t),s=chat.create();chat.submit(s.id,'Earlier','earlier-stop-test');await turn();chat.submit(s.id,'Skip me','skip-stop-test');chat.submit(s.id,'Later','later-stop-test');const skipped=chat.get(s.id).messages[3].id;chat.stop(s.id,skipped);assert.equal(calls[0].aborted,false);calls[0].resolve({text:'Earlier done'});await chat.idle();assert.equal(calls.length,1);assert.equal(chat.get(s.id).queue_paused,skipped);chat.resume(s.id,skipped);await turn();assert.equal(calls[1].message,'Later');calls[1].resolve({text:'Later done'});await chat.idle();
});
test('failed stop persistence leaves the request running and the stored decision unchanged',async t=>{
 const {chat,calls}=setup(t),s=chat.create();chat.submit(s.id,'Keep going','save-stop-test');await turn();const id=chat.get(s.id).messages[1].id,save=chat.save.bind(chat);chat.save=()=>{throw Error('disk failed');};assert.throws(()=>chat.stop(s.id,id),/still running/);assert.equal(calls[0].aborted,false);assert.equal(chat.get(s.id).messages[1].state,'working');assert.equal(chat.get(s.id).messages[1].stop_requested_at,undefined);chat.save=save;calls[0].resolve({text:'Finished'});await chat.idle();
});
test('a stopped reply waiting for an action review cannot dispatch afterward',async t=>{
 let finish;const {chat,calls}=setup(t,{runQuestion:(answer,waiting)=>{waiting('action');return new Promise((resolve,reject)=>{finish=()=>Promise.resolve().then(answer).then(resolve,reject);});}});const s=chat.create();chat.submit(s.id,'Waiting','review-stop-test');await turn();const id=chat.get(s.id).messages[1].id;chat.stop(s.id,id);finish();await chat.idle();assert.equal(calls.length,0);assert.equal(chat.get(s.id).messages[1].state,'interrupted');
});
test('HTTP stop uses existing CSRF protection and exact conversation/reply targeting',async t=>{
 const {chat,provider,dir,calls}=setup(t);const demo=createChatDemo({directory:dir,provider});await new Promise(r=>demo.server.listen(0,'127.0.0.1',r));t.after(()=>{demo.server.closeAllConnections();demo.server.close();});const origin=`http://127.0.0.1:${demo.server.address().port}`,url=origin+'/api/genie/chat',status=await(await fetch(url)).json();assert.equal(status.stop_reply_supported,true);const headers={'content-type':'application/json',origin,'x-dsg-csrf':status.csrf_token};const s=demo.chat.create();demo.chat.submit(s.id,'HTTP question','http-stop-test');await turn();const id=demo.chat.get(s.id).messages[1].id,body={action:'stop-reply',conversation_id:s.id,reply_id:id};assert.equal((await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})).status,403);assert.equal(calls[0].aborted,false);assert.equal((await fetch(url,{method:'POST',headers,body:JSON.stringify({...body,all:true})})).status,400);const response=await fetch(url,{method:'POST',headers,body:JSON.stringify(body)});assert.equal(response.status,202);await demo.chat.idle();assert.equal(calls[0].aborted,true);assert.equal(demo.chat.get(s.id).messages[1].state,'interrupted');
});

import http from 'node:http';import {hermesProvider} from './genie-hermes.mjs';
test('installed Hermes closes only the explicitly stopped turn while another reply completes',{
 skip:!process.env.DSG_TEST_HERMES_SOURCE||!process.env.DSG_TEST_HERMES_PYTHON,timeout:60000,
},async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sg-hermes-stop-')),held=new Map();
 const server=http.createServer((req,res)=>{if(req.method==='GET'){res.setHeader('content-type','application/json');res.end(JSON.stringify({data:[{id:'example-model'}]}));return;}let data='';req.on('data',c=>data+=c);req.on('end',()=>{const body=JSON.parse(data);if(!Array.isArray(body.messages)){res.writeHead(404,{'content-type':'application/json'});res.end(JSON.stringify({error:{message:'Synthetic endpoint not implemented',type:'not_found'}}));return;}const key=JSON.stringify(body.messages).includes('SYNTHETIC_KEEP_REPLY')?'keep':'stop';const record={res,body,closed:false};held.set(key,record);res.on('close',()=>record.closed=true);});});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const provider=hermesProvider({python:process.env.DSG_TEST_HERMES_PYTHON,source:process.env.DSG_TEST_HERMES_SOURCE,url:`http://127.0.0.1:${server.address().port}/v1`,model:'example-model'},{directory:dir});
 t.after(()=>{provider.close();server.closeAllConnections();server.close();fs.rmSync(dir,{recursive:true,force:true});});
 const chat=new GenieChat({directory:path.join(dir,'conversations'),provider}),a=chat.create(),b=chat.create();chat.submit(a.id,'SYNTHETIC_STOP_REPLY','native-stop-request');chat.submit(b.id,'SYNTHETIC_KEEP_REPLY','native-keep-request');
 const until=Date.now()+30000;while(held.size<2&&Date.now()<until)await new Promise(r=>setTimeout(r,50));assert.equal(held.size,2,'Both real Hermes bridges must reach the isolated HTTP provider');
 chat.stop(a.id,chat.get(a.id).messages[1].id);await chat.jobs.get(a.id);assert.equal(chat.get(a.id).messages[1].state,'interrupted');assert.equal(held.get('keep').closed,false,'Other request must remain connected');
 const closedBy=Date.now()+5000;while(!held.get('stop').closed&&Date.now()<closedBy)await new Promise(r=>setTimeout(r,25));assert.equal(held.get('stop').closed,true,'Stopped bridge must release its provider connection');
 const {res,body}=held.get('keep');const answer='Other reply completed.';
 if(body.stream){res.setHeader('content-type','text/event-stream');res.write(`data: ${JSON.stringify({id:'synthetic-keep',object:'chat.completion.chunk',model:'example-model',choices:[{index:0,delta:{role:'assistant',content:answer},finish_reason:null}]})}\n\n`);res.end(`data: ${JSON.stringify({id:'synthetic-keep',object:'chat.completion.chunk',model:'example-model',choices:[{index:0,delta:{},finish_reason:'stop'}]})}\n\ndata: [DONE]\n\n`);}else{res.setHeader('content-type','application/json');res.end(JSON.stringify({choices:[{message:{role:'assistant',content:answer},finish_reason:'stop'}],usage:{prompt_tokens:10,completion_tokens:4,total_tokens:14}}));}
 await chat.idle();assert.equal(chat.get(b.id).messages[1].state,'complete');assert.equal(chat.get(b.id).messages[1].text,answer);
});

test('stopping the last paused follow-up leaves no phantom queue pause',async t=>{const {chat,calls}=setup(t),s=chat.create();chat.submit(s.id,'First','empty-pause-first');await turn();chat.submit(s.id,'Last','empty-pause-last');const saved=chat.get(s.id);chat.stop(s.id,saved.messages[1].id);await chat.idle();chat.stop(s.id,saved.messages[3].id);assert.equal(chat.get(s.id).queued,0);assert.equal(chat.get(s.id).queue_paused,undefined);assert.equal(calls.length,1);});
