// Numerical tree evaluator only: no Python, child process or LLM on the request
// path. Export format is generated by the pinned trainer and parity-checked.
import {featureContract} from './prediction-feature-registry.mjs';
const finite=x=>typeof x==='number'&&Number.isFinite(x);
export function reference(f) {
  let value=finite(f.history_generation_estimate_s)?f.history_generation_estimate_s+(f.prior_ttft_s??0):f.same_prior_server===1&&finite(f.recent_service_mean)?f.recent_service_mean:f.worker_service_median??f.hardware_service_median??f.fleet_service_median;
  if(!finite(value))value=1;
  if(f.stage==='remaining')value=Math.max(1,value-(f.elapsed_s??0));
  return Math.max(1,value);
}
export function encode(features,encoding) {
  const result=[];
  for(const name of encoding.names){const value=features[name];
    if(encoding.categorical.includes(name)){const vocabulary=encoding.vocabulary[name],found=vocabulary.indexOf(value),at=found<0?vocabulary.length:found;for(let i=0;i<=vocabulary.length;i++)result.push(Number(i===at));}
    else result.push(finite(value)?Math.fround(value):NaN);
  }return result;
}
export function predictTreeModel(model,features) {
  const x=encode(features,model.encoding);let margin=Math.fround(model.base_margin);
  for(const t of model.trees){let i=0,hops=0;while(t.left_children[i]!==-1){if(++hops>16)throw new Error('Tree depth exceeded');const v=x[t.split_indices[i]],left=Number.isNaN(v)?!!t.default_left[i]:v<Math.fround(t.split_conditions[i]);i=left?t.left_children[i]:t.right_children[i];}margin=Math.fround(margin+Math.fround(t.split_conditions[i]));}
  const y=Math.max(0,(model.transform==='relative_log'?Math.expm1(margin+Math.log1p(reference(features))):model.transform==='log'?Math.expm1(margin):margin)*model.factor);
  if(!finite(y)||y>7*86400)throw new Error('Unsupported prediction magnitude');return y;
}
export function validateCandidate(bundle) {
  if(bundle.schema!==2||!bundle.models||!Number.isFinite(Date.parse(bundle.created_at)))throw new Error('Unsupported predictor bundle');
  const {FEATURE_NAMES,CATEGORICAL}=featureContract(bundle.feature_schema);
  for(const [kind,m] of Object.entries(bundle.models)){
    if(!['admission','updated','remaining'].includes(kind)||m.kind!==kind||!/^[a-f0-9]{64}$/.test(m.id)||!finite(m.base_margin)||!finite(m.factor)||m.factor<=0||!['raw','log','relative_log'].includes(m.transform))throw new Error('Unsupported model');
    const e=m.encoding;
    if(!Array.isArray(e?.names)||!e.names.length||new Set(e.names).size!==e.names.length||e.names.some(n=>!FEATURE_NAMES.includes(n))||!Array.isArray(e.categorical)||e.categorical.some(n=>!CATEGORICAL.includes(n)||!e.names.includes(n)))throw new Error('Invalid feature contract');
    for(const k of e.categorical)if(!Array.isArray(e.vocabulary?.[k])||e.vocabulary[k].length>256||new Set(e.vocabulary[k]).size!==e.vocabulary[k].length||e.vocabulary[k].some(x=>typeof x!=='string'||x.length>128))throw new Error('Invalid categorical encoding');
    const width=encode({},e).length;if(width!==e.encoded_names?.length||width>2048||!Array.isArray(m.trees)||m.trees.length>256)throw new Error('Invalid model width/size');
    for(const t of m.trees){const n=t.left_children?.length;if(!n||n>255||['right_children','split_indices','split_conditions','default_left'].some(k=>!Array.isArray(t[k])||t[k].length!==n))throw new Error('Invalid tree arrays');
      for(let i=0;i<n;i++){if(!finite(t.split_conditions[i]))throw new Error('Nonfinite tree');const l=t.left_children[i],r=t.right_children[i];if(l===-1){if(r!==-1)throw new Error('Invalid leaf');}else if(!Number.isInteger(l)||!Number.isInteger(r)||l<=i||r<=i||l>=n||r>=n||!Number.isInteger(t.split_indices[i])||t.split_indices[i]<0||t.split_indices[i]>=width)throw new Error('Invalid tree edge');}}
    if(!Array.isArray(m.parity)||!m.parity.length)throw new Error('Missing Python parity samples');
    for(const sample of m.parity)if(!finite(sample.seconds)||Math.abs(predictTreeModel(m,sample.features)-sample.seconds)>Math.max(.001,Math.abs(sample.seconds)*2e-5))throw new Error('Python/JavaScript predictor disagreement');
  }return bundle;
}
export function supported(model,point) {
  const s=model.support?.[point.node];return !!s&&s.requests>=10&&s.profiles?.includes(point.profile)&&(point.kind!=='remaining'||finite(s.max_elapsed_s)&&point.features.elapsed_s<=s.max_elapsed_s);
}
